version: "3"

services:
  httpd:
    image: php:7.2-apache
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env
